name: Deploy Static Website

on:
  push:
    branches:
      - main


permissions: 
  contents: read
  packages: write
  id-token: write


jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: Setup pages
       uses: actions/congigure-pages@v5

     - name: Upload Artifacts
       uses: actions/Uplopad-pages-artifacts@v3
       with:
       path: '.'

     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v4


    
